[fr-ch]
    languageCode = 'fr-CH'
    languageDirection = 'ltr'
    languageName = 'Français (Suisse)'
    weight = 1
[de-ch]
    languageCode = 'de-CH'
    languageDirection = 'ltr'
    languageName = 'Deutsch (Schweiz)'
    weight = 2
[en-us]
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2