[fr-ch]
    languageCode = 'fr-CH'
    languageDirection = 'ltr'
    languageName = 'FR'
    weight = 1
    [fr-ch.params]
        copyright = 'Tous droits réservés'
[de-ch]
    languageCode = 'de-CH'
    languageDirection = 'ltr'
    languageName = 'DE'
    weight = 2
    [de-ch.params]
        copyright = 'Alle Rechte vorbehalten'


[en-us]

    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'EN'
    weight = 3
    [en-us.params]
        copyright = 'All rights reserved'
