baseURL = 'https://transition.eco/'
languageCode = 'fr-ch'
title = 'transition'
theme = 'transition.eco'

defaultContentLanguage = 'fr-ch'
defaultContentLanguageInSubdir = true
    [languages]
        [languages.fr-ch]
            languageCode = 'fr-CH'
            languageDirection = 'ltr'
            languageName = 'Français (Suisse)'
            weight = 1
        [languages.de-ch]
            languageCode = 'de-CH'
            languageDirection = 'ltr'
            languageName = 'Deutsch (Schweiz)'
            weight = 2
        [languages.en-US]
            languageCode = 'en-US'
            languageDirection = 'ltr'
            languageName = 'English'
            weight = 2

[[menus.main]]
name = 'Accueil'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 20

    [[menus.main]]
    parent= 'Services'
    name = 'Analyser'
    pageRef = '/services/analyser'
    weight = 10

    [[menus.main]]
    parent= 'Services'
    name = 'Informer'
    pageRef = '/services/informer'
    weight = 20

    [[menus.main]]
    parent= 'Services'
    name = 'Former'
    pageRef = '/services/former'
    weight = 30

[[menus.main]]
name = 'Portrait'
pageRef = '/portrait'
weight = 30