baseURL = 'https://transition.eco/'
languageCode = 'fr-ch'
title = 'transition'
theme = 'transition.eco'

defaultContentLanguage = 'fr-ch'
defaultContentLanguageInSubdir = true
    [languages]
        [languages.fr-ch]
            languageCode = 'fr-CH'
            languageDirection = 'ltr'
            languageName = 'Français (Suisse)'
            weight = 1
        [languages.de-ch]
            languageCode = 'de-CH'
            languageDirection = 'ltr'
            languageName = 'Deutsch (Schweiz)'
            weight = 2
        [languages.en-US]
            languageCode = 'en-US'
            languageDirection = 'ltr'
            languageName = 'English'
            weight = 2