baseURL = 'https://transition.eco/'
languageCode = 'fr-ch'
title = 'Transition'

[[menus.main]]
name = 'Accueil'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 20

  [[menus.main]]
  parent= 'Services'
  name = 'Analyser'
  pageRef = '/services/analyser'
  weight = 10

  [[menus.main]]
  parent= 'Services'
  name = 'Informer'
  pageRef = '/services/informer'
  weight = 20

  [[menus.main]]
  parent= 'Services'
  name = 'Former'
  pageRef = '/services/former'
  weight = 30

[[menus.main]]
name = 'Portrait'
pageRef = '/portrait'
weight = 30

#[[menus.main]]
#name = 'Posts'
#pageRef = '/posts'
#weight = 20

#[[menus.main]]
#name = 'Tags'
#pageRef = '/tags'
#weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
