[[main]]
name = 'Home'
pageRef = '/'
weight = 10

[[main]]
name = 'Services'
pageRef = '/services'
weight = 20

    [[main]]
    parent= 'Services'
    name = 'Analysieren'
    pageRef = '/services/analyser'
    weight = 10

    [[main]]
    parent= 'Services'
    name = 'Informieren'
    pageRef = '/services/informer'
    weight = 20

    [[main]]
    parent= 'Services'
    name = 'Ausbilden'
    pageRef = '/services/former'
    weight = 30

[[main]]
name = 'Portrait'
pageRef = '/portrait'
weight = 30