[[main]]
name = 'Accueil'
pageRef = '/'
weight = 10

[[main]]
name = 'Services'
pageRef = '/services'
weight = 20

    [[main]]
    parent= 'Services'
    name = 'Analyser'
    pageRef = '/services/analyser'
    weight = 10

    [[main]]
    parent= 'Services'
    name = 'Informer'
    pageRef = '/services/informer'
    weight = 20

    [[main]]
    parent= 'Services'
    name = 'Former'
    pageRef = '/services/former'
    weight = 30


[[main]]
name = 'Projets'
pageRef = '/projects'
weight = 30

[[main]]
name = 'Portrait'
pageRef = '/portrait'
weight = 40

[[main]]
name = 'Contact'
pageRef = '/contact'
weight = 50