[[main]]
name = 'Home'
pageRef = '/'
weight = 10

[[main]]
name = 'Angebot'
pageRef = '/services'
weight = 20

    [[main]]
    parent= 'Angebot'
    name = 'Analysieren'
    pageRef = '/services/analyser'
    weight = 10

    [[main]]
    parent= 'Angebot'
    name = 'Informieren'
    pageRef = '/services/informer'
    weight = 20

    [[main]]
    parent= 'Angebot'
    name = 'Ausbilden'
    pageRef = '/services/former'
    weight = 30

[[main]]
name = 'Projekte'
pageRef = '/projects'
weight = 30

[[main]]
name = 'Portrait'
pageRef = '/portrait'
weight = 40

[[main]]
name = 'Kontakt'
pageRef = '/contact'
weight = 50